### ISSUE TITLE
ماژول دانشگاه

### ISSUE THREAD

**Issue by mostafa-binesh** [sina-rostami/Adobe-Connect-Based-Meetings#16]
سلام. میخوام پارامتر های ماژول دانشگاه شما رو به پارامتر های دانشگاه خودم تغییر بدم، ولی به مشکل خوردم، ورود با یوزر و پسورد وارد شده انجام میشه، ولی با خطای
Wrong URL format
مواجه میشم. جالب اینجاست که آدرسی که بهش میدم دقیقا فرم آدرس مثاله.
آدرس ورود سایت:
http://lms.sru.ac.ir/login/index.php
ساب دامین برای ادابی
https://vc.sru.ac.ir/
بخشی از کد ویرایش شده:

    kntu_login_data = {
    'anchor' : '',
    'username' : user_name,
    'password' : password,
    'rememberusername' : '0'
    }

    kntu_downloader = Downloader('http://lms.sru.ac.ir/login/index.php', # پارامتر اول، ورود سایت
    'https://vc.sru.ac.ir/', # ساب دامین ادابی سایت
    kntu_login_data, kntu_headers, kntu_headers)
    if not kntu_downloader.login({'logintoken'}):
        return

    for url in pasted_urls:
        if re.match(r'https://lms\d*\.sru\.ac\.ir/mod/adobeconnect/joinrecording\.php.*', url): # تغییر داده شده بر پایه ی آدرس ماژول دانشگاه نویسنده
            filename=re.findall('recording=(\d+)&', url)[0]
            print('Downloading ' + filename + '...')
            kntu_downloader.set_name_to_save(filename)
            kntu_downloader.set_pasted_url(url)
            kntu_downloader.set_cookies()
            if not kntu_downloader.create_downlaod_link():
                continue
            kntu_downloader.download_file()
            kntu_downloader.save_file()
            kntu_downloader.extract_zip_file()
            kntu_downloader.convert_media()
            kntu_downloader.download_other_files()
            print(filename + ' downloaded!')
        else:
            print('Wrong URL format')
            time.sleep(1) # واکنش سریعتر

    kntu_downloader.remove_temp_directory()

مقادیر info

> myusername
mypassword
http://lms.sru.ac.ir/mod/adobeconnect/joinrecording.php?id=51726&recording=12801780&groupid=0&sesskey=3D8SDHOszT
http://lms.sru.ac.ir/mod/adobeconnect/joinrecording.php?id=51726&recording=11435668&groupid=0&sesskey=3D8SDHOszT

**Comment by sina-rostami** [comment]
سلام این لینکی که از توی سایت کپی می‌کنید، مثلا
```
http://lms.sru.ac.ir/mod/adobeconnect/joinrecording.php?id=51726&recording=12801780&groupid=0&sesskey=3D8SDHOszT
```

روی پروتکل
`http`
هست  ولی تو اون شرط 

```
if re.match(r'https://lms\d*\.sru\.ac\.ir/mod/adobeconnect/joinrecording\.php.*', url):
```

داره پروتکل
`https`
رو مچ میزنه.
اگر تبدیل کنید به این:

```
if re.match(r'http://lms\d*\.sru\.ac\.ir/mod/adobeconnect/joinrecording\.php.*', url):
```
فکر می‌کنم درست بشه اگر مشکل دیگه ای نباشه.

در ضمن با توجه به اینکه کد در حال توسعه هست برای اینکه بتونید نسخه های بعدی هم داشته باشید ریپو رو فورک کنید و بعد از تغییرات مرج ریکوئست بدید تا از ریلیز بعدی ماژول دانشگاه شما رو هم منتشر کنم.

**Comment by mostafa-binesh** [comment]
بعد از درست کردن موردی که گفتید، باز به یه مشکل دیگه برخوردم که باز هم فکر میکنم بخاطر نداشتن
ssl 
سایت هستش.
کل کد
```
Preparing...
Logging in...
Logged in!
Downloading 12801780...
Setting cookies...
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connection.py", line 362, in connect
    self.sock = ssl_wrap_socket(
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\util\ssl_.py", line 386, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\ProgramData\Anaconda3\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\ProgramData\Anaconda3\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\ProgramData\Anaconda3\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\util\retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='vc.sru.ac.ir', port=443): Max retries exceeded with url: /pjoy1dj8ejow/?session=breezbreez3qrdfywuz2dtkgar (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sru.py", line 50, in <module>
    kntu_download(user_name, password, lines[2:])
  File "sru.py", line 30, in kntu_download
    kntu_downloader.set_cookies()
  File "C:\Users\UbiRo\Desktop\Adobe-Connect-Meetings-Downloader-master\downloader.py", line 58, in set_cookies
    self.meeting_page_req = self.dl_session.get(
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py", line 665, in send
    history = [resp for resp in gen]
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py", line 665, in <listcomp>
    history = [resp for resp in gen]
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py", line 237, in resolve_redirects
    resp = self.send(
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='vc.sru.ac.ir', port=443): Max retries exceeded with url: /pjoy1dj8ejow/?session=breezbreez3qrdfywuz2dtkgar (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))
```
پروتکل وریفای نمیشه و مشکل پیش میاد
```
requests.exceptions.SSLError: HTTPSConnectionPool(host='vc.sru.ac.ir', port=443): Max retries exceeded with url: /pjoy1dj8ejow/?session=breezbreez3qrdfywuz2dtkgar (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))
```
میشه فیکسش کرد؟
